### ISSUE TITLE
Attribute Values do not save price.

### ISSUE THREAD

**Issue by vwtdi2010** [pledra/odoo-product-configurator#60]
Impacted versions:
Current - Updated today.
Steps to reproduce:
Updating the price and save, price is always saved at $0.00
Current behavior:

Expected behavior:

Video/Screenshot link (optional):
see link below.
![untitled2](https://cloud.githubusercontent.com/assets/26640791/24710891/79033870-19ec-11e7-9e3f-1eca2a177917.png)

**Comment by PCatinean** [comment]
Hello @vwtdi2010 .

The price_extra field it normally not available in the form views of standard Odoo.

It has been added by accident in the product configurator and it is causing confusion.

The price_extra field is a computed field https://github.com/odoo/odoo/blob/10.0/addons/product/models/product_attribute.py#L29

And while it is possible to set prices this way since it implements a inverse method this is not how the pricing model currently works with the product configurator.

Please follow the documentation for setting up the prices of your components: https://www.pledra.com/odoo-product-configurator/documentation/functional/pricing.html

Thanks for reporting! The field will be removed from the view
